# Generated by Django 5.2.13 on 2026-06-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel_parser', '0005_parser_type_and_entity_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='channelcollectionitem',
            new_name='channel_par_owner_i_3c476b_idx',
            old_name='channel_col_owner_i_a0b5a9_idx',
        ),
        migrations.RenameIndex(
            model_name='channelcollectionitem',
            new_name='channel_par_templat_19fe81_idx',
            old_name='channel_col_templat_eb0ca5_idx',
        ),
        migrations.RenameIndex(
            model_name='channelcollectionitem',
            new_name='channel_par_templat_38c94c_idx',
            old_name='channel_col_templat_1a4e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='channelcollectionitem',
            new_name='channel_par_templat_e1b0f2_idx',
            old_name='channel_col_templat_7136f5_idx',
        ),
        migrations.RenameIndex(
            model_name='channelcollectiontemplate',
            new_name='channel_par_owner_i_c1b6f4_idx',
            old_name='channel_col_owner_i_e290ef_idx',
        ),
        migrations.RenameIndex(
            model_name='channelcollectiontemplate',
            new_name='channel_par_owner_i_a5b421_idx',
            old_name='channel_col_owner_i_37ee19_idx',
        ),
        migrations.RenameIndex(
            model_name='channelparsertemplate',
            new_name='channel_par_owner_i_2597b8_idx',
            old_name='channel_par_owner_i_814a0d_idx',
        ),
        migrations.RenameIndex(
            model_name='channelparsertemplate',
            new_name='channel_par_owner_i_0e7100_idx',
            old_name='channel_par_owner_i_547bb0_idx',
        ),
    ]
