# Generated by Django 5.2.13 on 2026-04-20 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='device_model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='health_score',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='quarantine_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='randomize_device_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='sleep_max_seconds',
            field=models.PositiveIntegerField(default=42),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='sleep_min_seconds',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='system_version',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='AccountHealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('flood_wait', 'Flood Wait'), ('spam_block', 'Spam Block'), ('success', 'Success')], max_length=32)),
                ('score_delta', models.SmallIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_events', to='telegram_accounts.telegramaccount')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['account', 'event_type', 'created_at'], name='telegram_ac_account_7a00a2_idx')],
            },
        ),
    ]
