# Generated by Django 5.2.13 on 2026-04-20 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0003_telegramaccount_device_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='attached_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='auth_phone_code_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='auth_state',
            field=models.CharField(choices=[('session_uploaded', 'Session Uploaded'), ('pending_code', 'Pending Code'), ('pending_2fa', 'Pending 2FA'), ('connected', 'Connected'), ('failed', 'Failed'), ('detached', 'Detached')], default='session_uploaded', max_length=32),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='detached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='is_attached',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='last_auth_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='requires_2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='session_file',
            field=models.FileField(blank=True, upload_to='telegram_sessions/'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='source',
            field=models.CharField(choices=[('session', 'Session'), ('credentials', 'Credentials')], default='session', max_length=32),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
