# Generated by Django 5.2.13 on 2026-04-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0004_telegramaccount_attached_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='auth_code_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='auth_code_timeout_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
