# Generated by Django 5.2.13 on 2026-04-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0005_telegramaccount_auth_code_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='role',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
