# Generated by Django 5.2.13 on 2026-04-22 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0006_telegramaccount_birth_date_telegramaccount_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='avatar',
            field=models.FileField(blank=True, upload_to='telegram_avatars/'),
        ),
        migrations.CreateModel(
            name='AccountRoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_role_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='role_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='telegram_accounts.accountroletemplate'),
        ),
        migrations.AddIndex(
            model_name='accountroletemplate',
            index=models.Index(fields=['owner', 'name'], name='telegram_ac_owner_i_d7acc3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountroletemplate',
            unique_together={('owner', 'name')},
        ),
    ]
