# Generated by Django 5.2.13 on 2026-04-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0007_telegramaccount_avatar_accountroletemplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramaccount',
            name='avatar',
        ),
    ]
