# Generated by Django 5.2.13 on 2026-06-02 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_accounts', '0008_remove_telegramaccount_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGGRRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В черзі'), ('running', 'Аналіз'), ('done', 'Готово'), ('failed', 'Помилка')], default='pending', max_length=16)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('potential', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('label', models.CharField(blank=True, choices=[('high', 'Високий'), ('medium', 'Середній'), ('low', 'Низький')], max_length=16)),
                ('survival_7d', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('survival_30d', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('median_lifetime_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('geo', models.CharField(blank=True, max_length=4)),
                ('similar_count', models.PositiveIntegerField(blank=True, null=True)),
                ('similar_params', models.CharField(blank=True, max_length=255)),
                ('factors', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.JSONField(blank=True, default=dict)),
                ('analysis', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ggr_ratings', to='telegram_accounts.telegramaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ggr_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['account', 'created_at'], name='telegram_ac_account_c2deae_idx'), models.Index(fields=['owner', 'created_at'], name='telegram_ac_owner_i_d594b1_idx')],
            },
        ),
    ]
