# Generated by Django 5.2.13 on 2026-04-21 13:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_accounts', '0005_telegramaccount_auth_code_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarmupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('behavior_profile', models.CharField(choices=[('safe', 'Safe'), ('balanced', 'Balanced'), ('aggressive', 'Aggressive')], default='safe', max_length=16)),
                ('daily_join_min', models.PositiveSmallIntegerField(default=5)),
                ('daily_join_max', models.PositiveSmallIntegerField(default=15)),
                ('delay_min_seconds', models.PositiveIntegerField(default=900)),
                ('delay_max_seconds', models.PositiveIntegerField(default=7200)),
                ('read_min_seconds', models.PositiveIntegerField(default=20)),
                ('read_max_seconds', models.PositiveIntegerField(default=180)),
                ('reaction_probability', models.PositiveSmallIntegerField(default=20)),
                ('max_reactions_per_day', models.PositiveSmallIntegerField(default=5)),
                ('retry_min_seconds', models.PositiveIntegerField(default=1800)),
                ('retry_max_seconds', models.PositiveIntegerField(default=10800)),
                ('active_start_hour', models.PositiveSmallIntegerField(default=8)),
                ('active_end_hour', models.PositiveSmallIntegerField(default=23)),
                ('allow_folder_one_click', models.BooleanField(default=False)),
                ('allow_public_gradual_join', models.BooleanField(default=True)),
                ('allow_private_join', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warmup_policies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WarmupTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('target_type', models.CharField(choices=[('channel', 'Channel'), ('folder', 'Folder')], default='channel', max_length=16)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=16)),
                ('value', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warmup_targets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WarmupPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounts', models.ManyToManyField(blank=True, related_name='warmup_plans', to='telegram_accounts.telegramaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warmup_plans', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='warmup.warmuppolicy')),
                ('targets', models.ManyToManyField(blank=True, related_name='warmup_plans', to='warmup.warmuptarget')),
            ],
        ),
        migrations.CreateModel(
            name='WarmupAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('join_channel', 'Join Channel'), ('join_folder', 'Join Folder'), ('read', 'Read'), ('reaction', 'Reaction')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=16)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('delay_seconds', models.PositiveIntegerField(default=0)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warmup_actions', to='telegram_accounts.telegramaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warmup_actions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='warmup.warmupplan')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='warmup.warmuptarget')),
            ],
        ),
        migrations.AddIndex(
            model_name='warmuppolicy',
            index=models.Index(fields=['owner', 'is_active'], name='warmup_warm_owner_i_bc4c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='warmuppolicy',
            index=models.Index(fields=['owner', 'behavior_profile'], name='warmup_warm_owner_i_1cbf0f_idx'),
        ),
        migrations.AddIndex(
            model_name='warmuptarget',
            index=models.Index(fields=['owner', 'status'], name='warmup_warm_owner_i_0e3585_idx'),
        ),
        migrations.AddIndex(
            model_name='warmuptarget',
            index=models.Index(fields=['owner', 'target_type', 'visibility'], name='warmup_warm_owner_i_9aa5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='warmupplan',
            index=models.Index(fields=['owner', 'status', 'created_at'], name='warmup_warm_owner_i_c307f5_idx'),
        ),
        migrations.AddIndex(
            model_name='warmupplan',
            index=models.Index(fields=['policy', 'status'], name='warmup_warm_policy__8383b2_idx'),
        ),
        migrations.AddIndex(
            model_name='warmupaction',
            index=models.Index(fields=['owner', 'status', 'scheduled_for'], name='warmup_warm_owner_i_e250b3_idx'),
        ),
        migrations.AddIndex(
            model_name='warmupaction',
            index=models.Index(fields=['plan', 'status', 'scheduled_for'], name='warmup_warm_plan_id_c28602_idx'),
        ),
        migrations.AddIndex(
            model_name='warmupaction',
            index=models.Index(fields=['account', 'status', 'scheduled_for'], name='warmup_warm_account_7626ce_idx'),
        ),
    ]
