# Generated by Django 5.2.13 on 2026-04-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warmup', '0004_warmuppolicy_runtime_controls'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='warmuplog',
            new_name='warmup_warm_owner_i_e3570e_idx',
            old_name='warmup_warm_owner_i_6b7434_idx',
        ),
        migrations.RenameIndex(
            model_name='warmuplog',
            new_name='warmup_warm_account_f0e917_idx',
            old_name='warmup_warm_account_3474fc_idx',
        ),
        migrations.RenameIndex(
            model_name='warmuplog',
            new_name='warmup_warm_plan_id_686234_idx',
            old_name='warmup_warm_plan_id_f7cf5d_idx',
        ),
    ]
