# Generated by Django 5.2.13 on 2026-06-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warmup', '0008_warmuppolicy_warmup_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='warmuppolicy',
            name='ai_protection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warmuppolicy',
            name='protection_mode',
            field=models.CharField(default='balanced', max_length=16),
        ),
    ]
