# Generated by Django 5.2.13 on 2026-04-24 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_accounts', '0008_remove_telegramaccount_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentParserJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('ai_protection', models.BooleanField(default=True)),
                ('fast_mode', models.BooleanField(default=False)),
                ('speed_mode', models.CharField(choices=[('safe', 'Safe'), ('balanced', 'Balanced'), ('fast', 'Fast')], default='balanced', max_length=16)),
                ('post_limit', models.PositiveIntegerField(default=50)),
                ('comment_limit', models.PositiveIntegerField(default=200)),
                ('days_limit', models.PositiveIntegerField(default=30)),
                ('skip_bots', models.BooleanField(default=True)),
                ('skip_deleted', models.BooleanField(default=True)),
                ('skip_scam', models.BooleanField(default=True)),
                ('only_with_username', models.BooleanField(default=False)),
                ('only_with_photo', models.BooleanField(default=False)),
                ('only_premium', models.BooleanField(default=False)),
                ('only_active_users', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='draft', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounts', models.ManyToManyField(blank=True, related_name='comment_parser_jobs', to='telegram_accounts.telegramaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_parser_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentParserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], default='info', max_length=16)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_parser_logs', to='telegram_accounts.telegramaccount')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='comment_parser.commentparserjob')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_parser_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ParsedCommenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('source_title', models.CharField(blank=True, max_length=255)),
                ('source_username', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=512)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('profile_url', models.URLField(blank=True, max_length=512)),
                ('is_bot', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_scam', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('has_photo', models.BooleanField(default=False)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('first_comment_at', models.DateTimeField(blank=True, null=True)),
                ('last_comment_at', models.DateTimeField(blank=True, null=True)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('sample_comment', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='comment_parser.commentparserjob')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_commenters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='commentparserjob',
            index=models.Index(fields=['owner', 'status', 'created_at'], name='comment_par_owner_i_7b0493_idx'),
        ),
        migrations.AddIndex(
            model_name='commentparserlog',
            index=models.Index(fields=['owner', 'created_at'], name='comment_par_owner_i_a0f29e_idx'),
        ),
        migrations.AddIndex(
            model_name='commentparserlog',
            index=models.Index(fields=['job', 'created_at'], name='comment_par_job_id_21625e_idx'),
        ),
        migrations.AddIndex(
            model_name='commentparserlog',
            index=models.Index(fields=['level'], name='comment_par_level_3563b9_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedcommenter',
            index=models.Index(fields=['owner', 'created_at'], name='comment_par_owner_i_f5ee51_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedcommenter',
            index=models.Index(fields=['job', 'comment_count'], name='comment_par_job_id_8533dd_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedcommenter',
            index=models.Index(fields=['username'], name='comment_par_usernam_819ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedcommenter',
            index=models.Index(fields=['telegram_user_id'], name='comment_par_telegra_ca20c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parsedcommenter',
            unique_together={('job', 'source_ref', 'telegram_user_id', 'username')},
        ),
    ]
