# Generated by Django 5.2.13 on 2026-05-23 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_accounts', '0008_remove_telegramaccount_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuroCommentPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neuro_comment_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('is_system', 'name'),
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='NeuroCommentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('use_ai_prompt', models.BooleanField(default=True)),
                ('comment_mode', models.CharField(choices=[('all', 'Всі пости'), ('keyword', 'За ключовими словами'), ('random', 'Випадкові')], default='all', max_length=16)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('random_probability', models.FloatField(default=0.5)),
                ('work_mode', models.CharField(choices=[('monitoring', 'Моніторинг нових постів'), ('count', 'За кількістю коментарів')], default='monitoring', max_length=16)),
                ('max_comments', models.PositiveIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('language_mode', models.CharField(choices=[('auto', 'Авто (визначати з поста)'), ('manual', 'Вручну')], default='auto', max_length=16)),
                ('language', models.CharField(blank=True, default='ru', max_length=8)),
                ('write_as_channel', models.BooleanField(default=False)),
                ('write_as_channel_username', models.CharField(blank=True, max_length=255)),
                ('auto_reply_enabled', models.BooleanField(default=False)),
                ('auto_reply_message', models.TextField(blank=True)),
                ('first_message_strategy', models.BooleanField(default=False)),
                ('first_message_text', models.CharField(blank=True, default='👍', max_length=64)),
                ('first_message_edit_delay', models.PositiveIntegerField(default=45)),
                ('account_rotation', models.BooleanField(default=True)),
                ('rotation_every_n', models.PositiveIntegerField(default=5)),
                ('comment_delay_min', models.FloatField(default=53.0)),
                ('comment_delay_max', models.FloatField(default=99.0)),
                ('entry_delay_min', models.FloatField(default=84.0)),
                ('entry_delay_max', models.FloatField(default=156.0)),
                ('ai_protection', models.BooleanField(default=True)),
                ('comments_sent', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='draft', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounts', models.ManyToManyField(blank=True, related_name='neuro_comment_jobs', to='telegram_accounts.telegramaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neuro_comment_jobs', to=settings.AUTH_USER_MODEL)),
                ('selected_prompts', models.ManyToManyField(blank=True, related_name='jobs', to='neuro_commenting.neurocommentprompt')),
            ],
        ),
        migrations.CreateModel(
            name='NeuroCommentBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_username', models.CharField(max_length=255)),
                ('reason', models.CharField(choices=[('flood_wait', 'FloodWait'), ('banned', 'Banned'), ('deleted', 'Comment deleted'), ('manual', 'Manual')], default='manual', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neuro_comment_blacklist', to='telegram_accounts.telegramaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neuro_comment_blacklist', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist', to='neuro_commenting.neurocommentjob')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['owner', 'channel_username'], name='neuro_comme_owner_i_abdbc2_idx')],
            },
        ),
        migrations.CreateModel(
            name='NeuroCommentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, max_length=255)),
                ('post_text', models.TextField(blank=True)),
                ('comment_text', models.TextField(blank=True)),
                ('prompt_name', models.CharField(blank=True, max_length=120)),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], default='info', max_length=16)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neuro_comment_logs', to='telegram_accounts.telegramaccount')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='neuro_commenting.neurocommentjob')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neuro_comment_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['owner', 'created_at'], name='neuro_comme_owner_i_95ce43_idx'), models.Index(fields=['job', 'created_at'], name='neuro_comme_job_id_79e004_idx'), models.Index(fields=['level'], name='neuro_comme_level_01a31c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='neurocommentjob',
            index=models.Index(fields=['owner', 'status', 'created_at'], name='neuro_comme_owner_i_83aeae_idx'),
        ),
    ]
