# Generated by Django 5.2.13 on 2026-05-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuro_commenting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neurocommentjob',
            name='protection_mode',
            field=models.CharField(choices=[('safe', 'Консервативний'), ('balanced', 'Збалансований'), ('fast', 'Агресивний')], default='balanced', max_length=16),
        ),
    ]
