# Generated by Django 5.2.13 on 2026-06-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reaction_bot', '0003_reactionjob_ai_features'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountchannelbinding',
            new_name='reaction_bo_owner_i_e41c86_idx',
            old_name='reaction_bo_owner_id_idx',
        ),
        migrations.RenameIndex(
            model_name='reactionjob',
            new_name='reaction_bo_owner_i_486f03_idx',
            old_name='reaction_bo_owner_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reactionlog',
            new_name='reaction_bo_owner_i_59d355_idx',
            old_name='reaction_bo_owner_created_idx',
        ),
        migrations.RenameIndex(
            model_name='reactionlog',
            new_name='reaction_bo_job_id_e90305_idx',
            old_name='reaction_bo_job_created_idx',
        ),
        migrations.RenameIndex(
            model_name='reactionlog',
            new_name='reaction_bo_level_8afee3_idx',
            old_name='reaction_bo_level_idx',
        ),
    ]
