# Generated by Django 5.2.13 on 2026-04-21 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_accounts', '0005_telegramaccount_auth_code_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=16)),
                ('age', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=120)),
                ('profession', models.CharField(max_length=160)),
                ('bio', models.CharField(blank=True, max_length=70)),
                ('photo', models.FileField(blank=True, upload_to='profile_generator/photos/')),
                ('photo_prompt', models.TextField(blank=True)),
                ('image_source', models.CharField(choices=[('none', 'None'), ('ai', 'AI'), ('upload', 'Upload')], default='none', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('applied', 'Applied'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_drafts', to='telegram_accounts.telegramaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['owner', 'status', 'created_at'], name='profile_gen_owner_i_a30f25_idx'), models.Index(fields=['account', 'status'], name='profile_gen_account_cbe81a_idx')],
            },
        ),
    ]
