# Generated by Django 5.2.13 on 2026-04-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledraft',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiledraft',
            name='telegram_channel',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='profiledraft',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
